//! Zero-cost message dispatcher
//! 
//! This module provides a compile-time message dispatch system that
//! avoids all dynamic dispatch for distributed messages.

use std::future::Future;
use std::pin::Pin;

use crate::actor::ActorId;
use crate::error::BoxError;

/// Type alias for a message handler function
pub type MessageHandler = fn(
    actor_id: ActorId,
    type_hash: u32,
    payload: &[u8],
) -> Pin<Box<dyn Future<Output = Result<(), BoxError>> + Send>>;

/// Trait that all distributed actors must implement
/// This is generated by the distributed_actor! macro
pub trait DistributedMessageHandler: Send + Sync {
    /// Handle a message based on its type hash
    fn handle_message(
        &mut self,
        type_hash: u32,
        payload: &[u8],
    ) -> Pin<Box<dyn Future<Output = Result<(), BoxError>> + Send + '_>>;
}